server:
  port: 8081
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: work
      password: 203811
      url: jdbc:mysql://47.110.51.219:3306/wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
